$ANSIBLE_VAULT;1.1;AES256
61623838346364663639653933633162663961336564323265336265353736356538303539663636
3361343838306562623331343965626338313737396461630a303761336533316631653431356638
64356431643338623064623464343961393031623737333565623333383332306462343565613864
6164663932653037610a633632663831326464323539373931656631306630626533383731626132
32316135393566316337633233663939656566363734633031386665623830663864396166656361
38656534333234623162633963653638353734323933306563396332393530323633653331656161
39366461363734316637613935666632636163383731383234666236666333313632383264656266
62333730656564333466326536633434623564306462303966326431383332386435653631376265
3634
