$ANSIBLE_VAULT;1.1;AES256
38373930393761326430343634633163396531393964316231366365633438313763626333653736
6165313535343566393664386139363238383435366365370a366261383262633066363737303336
63343235343232353632393761636566326138663730663865373165316238633266323261356236
3365366231313662650a333939616534316231336139653637363661666435343434323231303534
36373564623564643536616230343137636564613162383335353935313930626532396161643164
37646237383731386537356432393734306232386464333430353636663932393230373964633266
35383638313234663937316662323233316133343235346566616265633738656538633732633664
32643337313338306666303033313432373534633730666162663137646235343361363236393133
3131
